// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: vocab.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meaning       string                 `protobuf:"bytes,2,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Synonyms      []string               `protobuf:"bytes,3,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Example       string                 `protobuf:"bytes,4,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_vocab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_vocab_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Word) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *Word) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *Word) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_vocab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_vocab_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_vocab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vocab_proto_rawDescGZIP(), []int{2}
}

type ListWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []*Word                `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWordsResponse) Reset() {
	*x = ListWordsResponse{}
	mi := &file_vocab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsResponse) ProtoMessage() {}

func (x *ListWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsResponse.ProtoReflect.Descriptor instead.
func (*ListWordsResponse) Descriptor() ([]byte, []int) {
	return file_vocab_proto_rawDescGZIP(), []int{3}
}

func (x *ListWordsResponse) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_vocab_proto protoreflect.FileDescriptor

const file_vocab_proto_rawDesc = "" +
	"\n" +
	"\vvocab.proto\x12\x05vocab\x1a\x1cgoogle/api/annotations.proto\"j\n" +
	"\x04Word\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\ameaning\x18\x02 \x01(\tR\ameaning\x12\x1a\n" +
	"\bsynonyms\x18\x03 \x03(\tR\bsynonyms\x12\x18\n" +
	"\aexample\x18\x04 \x01(\tR\aexample\"'\n" +
	"\vAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\"6\n" +
	"\x11ListWordsResponse\x12!\n" +
	"\x05words\x18\x01 \x03(\v2\v.vocab.WordR\x05words2\xdb\x01\n" +
	"\fVocabService\x12@\n" +
	"\aAddWord\x12\v.vocab.Word\x1a\x12.vocab.AddResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/vocab\x12=\n" +
	"\rGetRandomWord\x12\f.vocab.Empty\x1a\v.vocab.Word\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/vocab\x12J\n" +
	"\tListWords\x12\f.vocab.Empty\x1a\x18.vocab.ListWordsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/vocab/allB7Z5github.com/mrkarna/vocabBuilder/backend/pb/autogen;pbb\x06proto3"

var (
	file_vocab_proto_rawDescOnce sync.Once
	file_vocab_proto_rawDescData []byte
)

func file_vocab_proto_rawDescGZIP() []byte {
	file_vocab_proto_rawDescOnce.Do(func() {
		file_vocab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_proto_rawDesc), len(file_vocab_proto_rawDesc)))
	})
	return file_vocab_proto_rawDescData
}

var file_vocab_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vocab_proto_goTypes = []any{
	(*Word)(nil),              // 0: vocab.Word
	(*AddResponse)(nil),       // 1: vocab.AddResponse
	(*Empty)(nil),             // 2: vocab.Empty
	(*ListWordsResponse)(nil), // 3: vocab.ListWordsResponse
}
var file_vocab_proto_depIdxs = []int32{
	0, // 0: vocab.ListWordsResponse.words:type_name -> vocab.Word
	0, // 1: vocab.VocabService.AddWord:input_type -> vocab.Word
	2, // 2: vocab.VocabService.GetRandomWord:input_type -> vocab.Empty
	2, // 3: vocab.VocabService.ListWords:input_type -> vocab.Empty
	1, // 4: vocab.VocabService.AddWord:output_type -> vocab.AddResponse
	0, // 5: vocab.VocabService.GetRandomWord:output_type -> vocab.Word
	3, // 6: vocab.VocabService.ListWords:output_type -> vocab.ListWordsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vocab_proto_init() }
func file_vocab_proto_init() {
	if File_vocab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_proto_rawDesc), len(file_vocab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vocab_proto_goTypes,
		DependencyIndexes: file_vocab_proto_depIdxs,
		MessageInfos:      file_vocab_proto_msgTypes,
	}.Build()
	File_vocab_proto = out.File
	file_vocab_proto_goTypes = nil
	file_vocab_proto_depIdxs = nil
}
