// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: vocab.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VocabService_AddWord_FullMethodName       = "/vocab.VocabService/AddWord"
	VocabService_GetRandomWord_FullMethodName = "/vocab.VocabService/GetRandomWord"
)

// VocabServiceClient is the client API for VocabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VocabServiceClient interface {
	AddWord(ctx context.Context, in *Word, opts ...grpc.CallOption) (*AddResponse, error)
	GetRandomWord(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Word, error)
}

type vocabServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVocabServiceClient(cc grpc.ClientConnInterface) VocabServiceClient {
	return &vocabServiceClient{cc}
}

func (c *vocabServiceClient) AddWord(ctx context.Context, in *Word, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, VocabService_AddWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabServiceClient) GetRandomWord(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Word, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Word)
	err := c.cc.Invoke(ctx, VocabService_GetRandomWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VocabServiceServer is the server API for VocabService service.
// All implementations must embed UnimplementedVocabServiceServer
// for forward compatibility.
type VocabServiceServer interface {
	AddWord(context.Context, *Word) (*AddResponse, error)
	GetRandomWord(context.Context, *Empty) (*Word, error)
	mustEmbedUnimplementedVocabServiceServer()
}

// UnimplementedVocabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVocabServiceServer struct{}

func (UnimplementedVocabServiceServer) AddWord(context.Context, *Word) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWord not implemented")
}
func (UnimplementedVocabServiceServer) GetRandomWord(context.Context, *Empty) (*Word, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomWord not implemented")
}
func (UnimplementedVocabServiceServer) mustEmbedUnimplementedVocabServiceServer() {}
func (UnimplementedVocabServiceServer) testEmbeddedByValue()                      {}

// UnsafeVocabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VocabServiceServer will
// result in compilation errors.
type UnsafeVocabServiceServer interface {
	mustEmbedUnimplementedVocabServiceServer()
}

func RegisterVocabServiceServer(s grpc.ServiceRegistrar, srv VocabServiceServer) {
	// If the following call pancis, it indicates UnimplementedVocabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VocabService_ServiceDesc, srv)
}

func _VocabService_AddWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Word)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabServiceServer).AddWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabService_AddWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabServiceServer).AddWord(ctx, req.(*Word))
	}
	return interceptor(ctx, in, info, handler)
}

func _VocabService_GetRandomWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabServiceServer).GetRandomWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabService_GetRandomWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabServiceServer).GetRandomWord(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VocabService_ServiceDesc is the grpc.ServiceDesc for VocabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VocabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vocab.VocabService",
	HandlerType: (*VocabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWord",
			Handler:    _VocabService_AddWord_Handler,
		},
		{
			MethodName: "GetRandomWord",
			Handler:    _VocabService_GetRandomWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vocab.proto",
}
